spring:
  application:
    name: kafka

kafka:
  bootstrap-servers:
    - localhost:29091
    - localhost:29092
    - localhost:29093
  example:
    topic: sample_example

logging:
  level:
    org.apache.kafka.clients.producer.KafkaProducer: DEBUG
    org.springframework.kafka.core.KafkaTemplate: DEBUG


